name: iShout
main: me.bfathman6.iShout.iShout
version: ${m.version}-${build.number}-${p.version}
MCMAPluginID: 13A44EB7-D013-4AD2-87E0-49CB2DAC6C08
author: bfathman6
website: http://mdev.in/
thread: http://forums.bukkit.org/threads/22958/
softdepend: [GroupManager, PermissionsBukkit, bPermissions, Spout, PermissionsEx]
description: Full Chat Customization
commands:
    iShout:
        usage: |
            [iShout] Help Screen
            - /<command> reload config = Reload Config.
            - /<command> reload info = Reload Info.
            - /<command> reload censor = Reload Censor.
            - /<command> reload locale = Reload Locale.
            - /<command> reload all = Reload All Configs.
            - /<command> user = Show Info User Help.
            - /<command> group = Show Info Group Help.
            - /<command> version = Show iShoutSuite Version.
        aliases: [iShout]
        ~permissions: iShout.reload.*, iShout.user.*, iShout.group.*
    iShoutme:
        usage: |
            /<command> *Message* - Displays message.
        aliases: [iShme]
        ~permissions: iShout.me
    iShoutwho:
        usage: |
            /<command> *PLAYER* - Displays info about player.
        aliases: [iShwho]
        ~permissions: iShout.who
    iShoutlist:
        usage: |
            /<command> - See A list of online players.
        aliases: [shlist, shonline, shplayerlist]
        ~permissions: iShout.list
    iShoutsay:
        usage: |
            /<command> *Message* - Broadcast a message.
        aliases: [iShsay]
        ~permissions: iShout.say
    iShoutafk:
        usage: |
            /<command> [REASON] - Displays you as AFK (REASON is optional).
        aliases: [iShafk, iShaway]
        ~permissions: iShout.afk.self
    iShoutafkother:
        usage: |
            /<command> *PLAYER* [REASON] - Displays *PLAYER* as AFK (REASON is optional).
        aliases: [shafkother, shafko, shawayother, shawayo]
        ~permissions: iShout.afk.other
    iShoutshout:
        usage: |
            /<command> - Broadcasts message overriding Local Chat.
        aliases: [shout, ishhyell]
        ~permissions: iShout.shout
    iShoutmute:
        usage: |
            /<command> [Player] - Mutes a player.
        aliases: [shmute]
        ~permissions: iShout.mute
    iShoutmessageprefix:
        usage: |
            /<command> set *Prefix* - Adds a Prefix to chat messages.
            /<command> remove - Removes the Prefix from chat messages.
        aliases: [iShoutprefix, iShprefix, iShprefix]
        ~permissions: iShout.messageprefix
    piShout:
        usage: |
            /<command> {player} *Message* - Sends PM to player.
        aliases: [iShouttell, ishtell, ishmsg, ishmessage]
        ~permissions: iShout.pm.pm
    piShoutreply:
        usage: |
            /<command> *Message* - Sends Reply to a players PM.
        aliases: [piShoutr, pmreply, pmr, reply]
        ~permissions: iShout.pm.reply
    piShoutinvite:
        usage: |
            /<command> {player} - Sends a private Convo invitation to player.
        aliases: [piShouti, pminvite, pmi, pinvite]
        ~permissions: iShout.pm.invite
    piShoutaccept:
        usage: |
            /<command> - Accept pending Convo.
        aliases: [piShouta, pmaccept, pma, paccept]
    piShoutdeny:
        usage: |
            /<command> - Deny pending Convo.
        aliases: [piShoutd, pmdeny, pmd, pdeny]
    piShoutleave:
        usage: |
            /<command> - Ends convo.
        aliases: [piShoutl, pmleave, pml, pleave]
    mchannel:
        aliases: [ishchann, ishchan]
permissions:
    iShout.*:
        default: false
        description: Allows full use of iShout.
        children:
            iShout.reload.*: true
            iShout.suppress.*: true
            iShout.pm.*: true
            iShout.afk.*: true
            iShout.bypass.*: true
            iShout.user.*: true
            iShout.group.*: true
            iShout.coloredchat: true
            iShout.censorbypass: true
            iShout.me: true
            iShout.list: true
            iShout.who: true
            iShout.version: true
            iShout.shout: true
            iShout.spy: true
            iShout.messageprefix: true
            iShout.mute: true
    iShout.reload.*:
        default: false
        description: Allow usage of /iShout reload '[config/info/censor/locale/all]'
        children:
            iShout.reload.config: true
            iShout.reload.info: true
            iShout.reload.censor: true
            iShout.reload.locale: true
            iShout.reload.all: true
    iShout.suppress.*:
        default: false
        description: Allow usage suppression of all messages.
        children:
            iShout.suppress.join: true
            iShout.suppress.quit: true
            iShout.suppress.kick: true
            iShout.suppress.death: true
    iShout.pm.*:
        default: false
        description: Allow usage of all PM functions
        children:
            iShout.pm.pm: true
            iShout.pm.reply: true
            iShout.pm.invite: true
    iShout.afk.*:
        default: false
        description: Allow usage of all PM functions
        children:
            iShout.afk.self: true
            iShout.afk.other: true
    iShout.bypass.*:
        default: false
        description: Allow bypass of all Automatic functions.
        children:
            iShout.bypass.afk: true
            iShout.bypass.afkkick: true
            iShout.bypass.suppress.*: true
    iShout.bypass.suppress.*:
        default: false
        description: Allow bypass of all Override functions.
        children:
            iShout.bypass.suppress.join: true
            iShout.bypass.suppress.quit: true
            iShout.bypass.suppress.kick: true
            iShout.bypass.suppress.death: true
    iShout.user.*:
        default: false
        description: Allows full use of all user info related iShout commands.
        children:
            iShout.user.add.*: true
            iShout.user.set.*: true
            iShout.user.remove.*: true
    iShout.group.*:
        default: false
        description: Allows full use of all group info related iShout commands.
        children:
            iShout.group.add.*: true
            iShout.group.remove.*: true
    iShout.user.add.*:
        default: false
        description: Allows full use of all user info add iShout commands.
        children:
            iShout.user.add.player: true
            iShout.user.add.ivar: true
            iShout.user.add.world: true
            iShout.user.add.wvar: true
    iShout.user.set.*:
        default: false
        description: Allows full use of all user info set iShout commands.
        children:
            iShout.user.set.group: true
    iShout.user.remove.*:
        default: false
        description: Allows full use of all user info remove iShout commands.
        children:
            iShout.user.remove.player: true
            iShout.user.remove.ivar: true
            iShout.user.remove.world: true
            iShout.user.remove.wvar: true
    iShout.group.add.*:
        default: false
        description: Allows full use of all group info add iShout commands.
        children:
            iShout.group.add.group: true
            iShout.group.add.ivar: true
            iShout.group.add.world: true
            iShout.group.add.wvar: true
    iShout.group.remove.*:
        default: false
        description: Allows full use of all group info remove iShout commands.
        children:
            iShout.group.remove.group: true
            iShout.group.remove.ivar: true
            iShout.group.remove.world: true
            iShout.group.remove.wvar: true
    iShout.reload.config:
        default: false
        description: Allow usage of /iShout reload config
    iShout.reload.info:
        default: false
        description: Allow usage of /iShout reload info
    iShout.reload.censor:
        default: false
        description: Allow usage of /iShout reload censor
    iShout.reload.locale:
        default: false
        description: Allow usage of /iShout reload locale
    iShout.reload.all:
        default: false
        description: Allow usage of /iShout reload all
    iShout.coloredchat:
        default: false
        description: Allow colour in chat messages.
    iShout.censorbypass:
        default: false
        description: Allow bypass of msg censoring.
    iShout.me:
        default: false
        description: Allow use of the /iShoutme command.
    iShout.afk:
        default: false
        description: Allow use of the /iShoutafk command.
    iShout.afkother:
        default: false
        description: Allow use of the /iShoutafkother command.
    iShout.shout:
        default: false
        description: Allow use of the /iShoutshout command.
    iShout.list:
        default: false
        description: Allow use of the /iShoutlist command.
    iShout.who:
        default: false
        description: Allow use of the /iShoutwho command.
    iShout.version:
        default: false
        description: Allow use of the /iShout version command.
    iShout.spy:
        default: false
        description: Allows player to view all chat messages.
    iShout.messageprefix:
        default: false
        description: Allows player to add a prefix to their message.
    iShout.mute:
        default: false
        description: Allows muting and unmuting of players.
    iShout.suppress.join:
        default: false
        description: Allow suppression of the iShout Join Messages.
    iShout.suppress.quit:
        default: false
        description: Allow suppression of the iShout Quit Messages.
    iShout.suppress.kick:
        default: false
        description: Allow suppression of the iShout Kick Messages.
    iShout.suppress.death:
        default: false
        description: Allow suppression of the iShout Death Messages.
    iShout.pm.pm:
        default: false
        description: Allow use of the /piShout command.
    iShout.pm.reply:
        default: false
        description: Allow use of the /piShoutreply command.
    iShout.pm.invite:
        default: false
        description: Allow use of the /piShoutinvite command.
    iShout.bypass.afk:
        default: false
        description: Allow bypassing of AutoAFK.
    iShout.bypass.afkkick:
        default: false
        description: Allow bypassing of AutoAFK Kick.
    iShout.bypass.suppress.join:
        default: false
        description: Allow bypassing of Join Suppression.
    iShout.bypass.suppress.quit:
        default: false
        description: Allow bypassing of Quit Suppression.
    iShout.bypass.suppress.kick:
        default: false
        description: Allow bypassing of Kick Suppression.
    iShout.bypass.suppress.death:
        default: false
        description: Allow bypassing of Death Suppression.
    iShout.user.add.player:
        default: false
        description: Allow usage of /iShout user add player Player
    iShout.user.add.ivar:
        default: false
        description: Allow usage of /iShout user add ivar Player InfoVariable InfoValue
    iShout.user.add.world:
        default: false
        description: Allow usage of /iShout user add world Player World
    iShout.user.add.wvar:
        default: false
        description: Allow usage of /iShout user add world Player World InfoVariable InfoValue
    iShout.user.set.group:
        default: false
        description: Allow usage of /iShout user set group Player NewGroup
    iShout.user.remove.player:
        default: false
        description: Allow usage of /iShout user remove Player
    iShout.user.remove.ivar:
        default: false
        description: Allow usage of /iShout user remove Player InfoVariable
    iShout.user.remove.world:
        default: false
        description: Allow usage of /iShout user remove Player World
    iShout.user.remove.wvar:
        default: false
        description: Allow usage of /iShout user remove Player World InfoVariable
    iShout.group.add.group:
        default: false
        description: Allow usage of /iShout group add group Group
    iShout.group.add.ivar:
        default: false
        description: Allow usage of /iShout group add ivar Group InfoVariable InfoValue
    iShout.group.add.world:
        default: false
        description: Allow usage of /iShout group add world Group World
    iShout.group.add.wvar:
        default: false
        description: Allow usage of /iShout group add world Group World InfoVariable InfoValue
    iShout.group.remove.group:
        default: false
        description: Allow usage of /iShout group remove group Group
    iShout.group.remove.ivar:
        default: false
        description: Allow usage of /iShout group remove ivar Group InfoVariable
    iShout.group.remove.world:
        default: false
        description: Allow usage of /iShout group remove world Group World
    iShout.group.remove.wvar:
        default: false
        description: Allow usage of /iShout group remove wvar Group World InfoVariable